[PHP]
memory_limit = 64M
max_execution_time = 30
date.timezone = UTC

[opcache]
opcache.enable=1
opcache.enable_cli=0
opcache.memory_consumption=32
opcache.max_accelerated_files=4000
opcache.validate_timestamps=0
